package com.sphtest.data.db.tables;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sphtest.data.db.tables.VolumeDataTable;

import com.sphtest.data.db.tables.VolumeDataTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig volumeDataTableDaoConfig;

    private final VolumeDataTableDao volumeDataTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        volumeDataTableDaoConfig = daoConfigMap.get(VolumeDataTableDao.class).clone();
        volumeDataTableDaoConfig.initIdentityScope(type);

        volumeDataTableDao = new VolumeDataTableDao(volumeDataTableDaoConfig, this);

        registerDao(VolumeDataTable.class, volumeDataTableDao);
    }
    
    public void clear() {
        volumeDataTableDaoConfig.clearIdentityScope();
    }

    public VolumeDataTableDao getVolumeDataTableDao() {
        return volumeDataTableDao;
    }

}
